AWSTemplateFormatVersion: "2010-09-09"

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket

    Properties:
      BucketName: !Sub "${AWS::AccountId}-frontend-s3"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

      # Block all public access:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
